### ISSUE TITLE
NTR: Request for P02 Coral infection and damage parameters

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/P02#1]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Coral infection and damage parameters <p><b>Definition</b><p> Parameters used to quantify the health and conservation status of single and multi-species coralligenous colonies and communities.<p><H2> Optional </H2><p><b>Sources/references</b><p> Relates to NTR https://github.com/nvs-vocabs/P01/issues/35 Tried to align it to an existing P02 parameter set up for macroalgae and seagrass [GP012](http://vocab.nerc.ac.uk/collection/P02/current/GP012/)<p> <b>Mapping to other terminologies </b><p> Is related to GOOS EOV [Hard coral cover and composition](https://goosocean.org/index.php?option=com_oe&task=viewDocumentRecord&docID=17512)<p>

Suggesting links to the following P03 categories:
http://vocab.nerc.ac.uk/collection/P03/current/B060/
http://vocab.nerc.ac.uk/collection/P03/current/B070/
http://vocab.nerc.ac.uk/collection/P03/current/G055/
http://vocab.nerc.ac.uk/collection/P03/current/B007/
http://vocab.nerc.ac.uk/collection/P03/current/H001/

**Comment by gwemon** [comment]
New code published on the NVS: http://vocab.nerc.ac.uk/collection/P02/current/GP013/
Please note small change to the descriptive text.
Any issues please reopen this ticket.
