### ISSUE TITLE
Proposal to combine existing 'raw instrument output' P02 terms into a singular term

### ISSUE THREAD

**Issue by danibodc** [nvs-vocabs/P02#10]
We currently have the following terms in P02 in relation to various raw instrument outputs:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/dangar/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/dangar/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Preferred   label | URI
-- | --
Raw in-situ nutrient analyser output | http://vocab.nerc.ac.uk/collection/P02/current/NUTV
Raw suspended particulate material   concentration sensor output | http://vocab.nerc.ac.uk/collection/P02/current/TVLT
Raw gas analyser output | http://vocab.nerc.ac.uk/collection/P02/current/RGAS
Raw fluorometer output | http://vocab.nerc.ac.uk/collection/P02/current/FVLT
Raw oxygen   sensor output | http://vocab.nerc.ac.uk/collection/P02/current/OXYC
Raw temperature and/or salinity instrument output | http://vocab.nerc.ac.uk/collection/P02/current/TCNT
Raw light meter   output | http://vocab.nerc.ac.uk/collection/P02/current/LVLT
Raw current   meter output parameters | http://vocab.nerc.ac.uk/collection/P02/current/LERR
Raw pH sensor   output | http://vocab.nerc.ac.uk/collection/P02/current/PHLT

</body>

</html>

Here we propose to combine these into a single P02 term as below:

- Raw instrument output
Definition: Raw parameter outputs expressed as voltages or counts from a sensor, instrument or analyser. 

The existing P02 terms will be deprecated and re-mapped to the new term.

**Comment by gwemon** [comment]
Hi Roy, @roy-lowry can you see any issue with this proposal? If we go ahead with it then we would have to review all the mappings attached to the existing terms. But this being raw data I can't see a reason why they should have separate P02 categories.

**Comment by roy-lowry** [comment]
Looks OK to me.

**Comment by danibodc** [comment]
After some further discussion on this we have decided to instead create a new P02 related to raw output from microstructure sensors, rather than deprecating the above categories and re-mapping them to a new broader category. 

If we had a single broader category, we are concerned that users who may be harvesting our terms based on the P02 would not directly find raw nutrient outputs when they are looking for raw optical outputs, for example. 

Proposed new P02:
**Preferred label:** Raw microstructure sensor output
**Description:**  Raw direct output parameters from microstructure sensors, probes or profilers that are used to determine the distribution of water body properties on a millimetric scale.

This would align with L05 - microstructure sensors: http://vocab.nerc.ac.uk/collection/L05/current/184

**Comment by gwemon** [comment]
Alternatively we could label the new P02 "Raw turbulence sensor output". Both work for me. The new P02 would be linked to the APG http://vocab.nerc.ac.uk/collection/P03/current/D030/ the same way as P02 for [Turbulence in the water body](http://vocab.nerc.ac.uk/collection/P02/current/EPSI/) is linked to D030.

**Comment by danibodc** [comment]
Thanks @gwemon I prefer this!

**Comment by roy-lowry** [comment]
Brain wasn't engaged when I said the initial proposal looked OK. The reason these categories were set up was to provide a way to allow all datasets for a given type of measurement to be discovered as Dani pointed out whilst providing a mechanism for those with no interest in unprocessed data to filter them out. Like Dani I like Gwen's suggestion.

**Comment by danibodc** [comment]
The term is now live on the NVS:
http://vocab.nerc.ac.uk/collection/P02/current/EPSV/
