### ISSUE TITLE
NTR: Lake and river water level parameters

### ISSUE THREAD

**Issue by danibodc** [nvs-vocabs/P02#14]
<H2> Required </H2><p><b>Code</b><p>LRWL<p><b>Term name (PrefLabel)</b><p>Lake and river water level parameters<p><b>Definition</b><p> Parameters describing the vertical distance (height or elevation) of river or lake water from a specified point of reference to the water's surface.<p>

**Comment by danibodc** [comment]
Related to P01 request: https://github.com/nvs-vocabs/P01/issues/202

**Comment by roy-lowry** [comment]
Need to have a clear definition of what is meant by 'river' here. There are tide gauges in the River Mersey that are very much sea level! I would suggest qualifying rivers as being upstream from the tidal limit.

**Comment by danibodc** [comment]
LRWL	Lake and river water level parameters

Definition:
Parameters describing the vertical distance (height or elevation) of river or lake water from a specified point of reference to the water's surface. Rivers are defined as being upstream from the tidal limit.

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/P02/current/LRWL/
