### ISSUE TITLE
Expansion of Fish reproduction description

### ISSUE THREAD

**Issue by roswri** [nvs-vocabs/P02#15]
http://vocab.nerc.ac.uk/collection/P02/current/FREP

**current description:** Parameters that quantify the fecundity, reproductive rates or nature of reproduction in fish (Osteichthyes, Agnatha and Chrondrichthyes).

**Suggested expansion**: Parameters that quantify the fecundity, reproductive rates or nature of reproduction in fish (Osteichthyes, Agnatha and Chrondrichthyes), and describe the characteristics and location of spawning and nursery grounds.

**Comment by neil-ices-dk** [comment]
Dear BODC colleagues,

I'm struggling a bit with the expansion of the concept as it seems to go beyond the headline description of the concept, at least it needs some more thought on the proposed definition.

I was also wondering if the proposed definition could be aligned to http://vocab.nerc.ac.uk/collection/P02/current/GP087/ _Parameters describing the extent, intensity, timing and method of fisheries_  as this seems a more logical description 

Thanks, Neil

**Comment by gwemon** [comment]
Thanks @neil-ices-dk We did hesitate indeed between the two. I leaned towards expansion of the http://vocab.nerc.ac.uk/collection/P02/current/FREP rather than http://vocab.nerc.ac.uk/collection/P02/current/GP087/ because  observations and measurements related to "spawning grounds" might not always be related to "fisheries"? Or am I being too narrow in my interpretation of the term "fisheries"?

**Comment by neil-ices-dk** [comment]
Thanks @gwemon I agree that it might not be synonymous with fisheries. What I intended by my comment was that you adapt your FREP concept description to be described in a similar format to GP087. 

Fisheries could include biological and geological components, depending on how you read the FAO definition, which incidentally would be the guide for concepts on spawning and nursery grounds etc.
https://agrovoc.fao.org/skosmosAsfa/asfa/en/page/?uri=http%3A%2F%2Faims.fao.org%2Faos%2Fagrovoc%2Fc_2934

**Comment by gwemon** [comment]
Excellent thanks @neil-ices-dk  we will link our "spawning grounds" to the FAO URI http://aims.fao.org/aos/agrovoc/c_7277 in the NVS.
So is what you are suggesting to expand the definition of [GP087]( http://vocab.nerc.ac.uk/collection/P02/current/GP087/) as follows: Parameters describing the location, extent, intensity, timing and method of fisheries?
Rob Thomas had suggested this too.
or shall we specify "spawning grounds" at the P02 level as in: 
Parameters describing the location, extent, intensity, timing and method of fisheries, spawning and nursery grounds?

**Comment by neil-ices-dk** [comment]
> So is what you are suggesting to expand the definition of [GP087](http://vocab.nerc.ac.uk/collection/P02/current/GP087/) as follows: Parameters describing the location, extent, intensity, timing and method of fisheries?

yes - this one 👍

**Comment by roswri** [comment]
Just want to check I've followed the discussion correctly, the definition of [GP087](http://vocab.nerc.ac.uk/collection/P02/current/GP087/) is already: Parameters describing the location, extent, intensity, timing and method of fisheries.

So the proposal is to amend the definition of [Fish reproduction - FREP](https://vocab.nerc.ac.uk/collection/P02/current/FREP/) to have a similar format i.e. _Parameters describing the extent, intensity, timing and method of reproduction in fish (Osteichthyes, Agnatha and Chrondrichthyes) including fecundity, reproductive rates, spawning, and nursery grounds._
Or something along those lines, is that right?
