### ISSUE TITLE
NTR: Request for P02 Concentration of aliphatic hydrocarbons in surface water samples

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/P02#17]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Concentration of aliphatic hydrocarbons in surface water samples <p><b>Definition</b><p> Sum concentration of aliphatic hydrocarbons (AHs) in water samples <p><H2> Optional </H2><p><b>Synonym or acronym (AltLabel)</b><p> Total AHs in water; Aliphatic hydrocarbons concentration in water<p><b>Mapping to other terminologies </b><p> Total AHs in water; Aliphatic hydrocarbons concentration in water<p>

**Comment by melinalou** [comment]
Can you give me some information about the "invalid"?

**Comment by gwemon** [comment]
@melinalou I believe that @danibodc has been in touch with you already and it was established that these were not P02 requests but P01? see: https://github.com/nvs-vocabs/P01/issues/276 
But if any of these need to be reopened as P02 requests then please let us know.

**Comment by melinalou** [comment]
Oh yes, thank you for the information!
