### ISSUE TITLE
NTR: Request for P02 Ocean mixed layer depth (BODCNVS-749)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/P02#3]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Ocean mixed layer depth <p><b>Definition</b><p> Upper part of the ocean regarded as being well-mixed<p><H2> Optional </H2><p><b>Sources/references</b><p> http://www.ifremer.fr/cerweb/deboyer/mld/Surface_Mixed_Layer_Depth.php<p>

**Comment by gwemon** [comment]
Consulting requester.

**Comment by gwemon** [comment]
The request was related to submission of a data product to the SeaDataNet Sextant catalogue. Advised requester to use  https://vocab.nerc.ac.uk/collection/P02/current/MXLM/
