### ISSUE TITLE
NTR: Request for P02 Pesticide concentrations in suspended particulate material (BODCNVS-1013)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/P02#5]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Pesticide concentrations in suspended particulate material <p><b>Definition</b><p> Concentration parameters for substances synthesised by man to kill other life forms in suspended particulate material (SPM) collected by water column filtration, centrifugation or sediment trapping. Only includes parameters expressed per unit mass of SPM and not per unit volume of the water column.<p><H2> Optional </H2><p><b>Sources/references</b><p> BODCNVS-1013: EMODnet chemistry request. Used existing pesticide and SPM codes and definitions in P02 as templates for the new term to be consistent.<p> <b>Mapping to other terminologies </b><p> will need to be mapped to: http://vocab.nerc.ac.uk/collection/P03/current/H001/ ; http://vocab.nerc.ac.uk/collection/P36/current/PESTBI/ ; and http://vocab.nerc.ac.uk/collection/L04/current/L04001/ <p>

**Comment by gwemon** [comment]
New term added to the NVS: http://vocab.nerc.ac.uk/collection/P02/current/PESP/
