### ISSUE TITLE
Extend the definition of existing code AMOX to include nitrification and denitrification in water bodies

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P02#7]
I am proposing to extend the definition of http://vocab.nerc.ac.uk/collection/P02/current/AMOX/ in order to include parameters that quantify both nitrification and denitrification in water bodies. The reason to prefer this over creating a separate P02 Parameter Discovery code for denitrification is that both are often measured together or in parallel experiments and creating separate codes for the 2 processes would complicate marking and discovery. It is also in line with our P02 management strategy to only create new concepts when broadening of existing concepts is not an option. This is linked to request [nvs-vocab/P01#98](https://github.com/nvs-vocabs/P01/issues/98)
Please let me know if there are any issues with this proposal. Thank you.

The new concept preferred label and definition would be:
Preferred label: Nitrification and denitrification rates in water bodies
Definition: Parameters quantifying rates associated with nitrification (oxidation of reduced nitrogen such as ammonium) and denitrification (conversion of nitrate into gaseous compounds such as nitric oxide, nitrous oxide and molecular nitrogen) processes in the water column of any body of fresh or salt water.

**Comment by roy-lowry** [comment]
Makes sense to me.

**Comment by gwemon** [comment]
Changes made and published on NVS: http://vocab.nerc.ac.uk/collection/P02/current/AMOX/
