### ISSUE TITLE
NTR for parameters related to single particle analysis in any media

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/P02#9]
This is related to a request for new P01 codes to support EMODnet chemistry micro-litter data workflows. New techniques now enable analysis of particle properties (length, width but possibly more) to be reported with their identifier at the single particle level. The EMODnet chemistry group would prefer if the code were not made to be matrix dependent and as currently envisaged, the P01 codes will not be specific to micro-plastic.
So I am proposing to create a new Parameter Discovery concept for "Single particle properties". Any comments or advice? Have I missed a suitable existing code to cover this?
This relates to this P01 ticket: https://github.com/nvs-vocabs/P01/issues/127

**Comment by roy-lowry** [comment]
There is the bucket term 'other physical and chemical properties of suspended particulate material'
 (http://vocab.nerc.ac.uk/collection/P02/current/DENS/ ), but it's a little ugly (definition looks a lot like desperation) and specifies a matrix so a new category would be better.
How about a title like 'particle characterisation' with a definition like 'Physical or chemical properties of individual sediment grains or individual solid particles suspended in water or air' to make matrix independence explicit.?

**Comment by gwemon** [comment]
Thank you @roy-lowry  I quite like your suggestion of using DENS for the time being though. I had not noticed it. It fits these kinds of parameters. It'll allow us to create the new P01 codes without rushing the decision about the new P02.

**Comment by gwemon** [comment]
> 
For the new P02, I do like your suggestion @roy-lowry  but I think we need to say in the name of the P02 that these are for _single_ particles to make it completely unambiguous. And for the definition I think we need to stay away from specifying what the particle is and where it is. Because these parameters may relate to particles of microplastic in the flesh of organisms for example. So how about:

Preferred label: Single particle characterisation
Definition: Physical, chemical or optical properties of individual solid particles.

@roy-lowry @mmolinajack @mattevi78

**Comment by mmolinajack** [comment]
Thanks @roy-lowry and @gwemon, we agree with the proposal.

**Comment by danibodc** [comment]
The P02 term has been loaded and will be live on the NVS from tomorrow morning:

SPCN	Single particle characterisation

I have also updated the group_code to SPCN in PARAM_ATTR to the associated P01s (SPIDXX01, SPWDXX01, SPLGXX01).

**Comment by danibodc** [comment]
http://vocab.nerc.ac.uk/collection/P02/current/SPCN/
